# Generated by Django 3.2.10 on 2022-02-26 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='categories_slug',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='gallery_slug',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_slug',
        ),
    ]
